### ISSUE TITLE
Sample Setup - Sample.js does not exist

### ISSUE THREAD

**Issue by unicodeveloper** [toystars/elasticsearch-sync#1]
<img width="970" alt="screen shot 2016-04-22 at 7 50 20 pm" src="https://cloud.githubusercontent.com/assets/2946769/14751775/89ca8b4e-08c3-11e6-8f29-b6ccc7c8e39b.png">

**Comment by toystars** [comment]
@unicodeveloper thanks for checking it up. File has been added and linked. :+1:
