### ISSUE TITLE
Passing _id in main body field is no longer valid. 

### ISSUE THREAD

**Issue by siyong** [toystars/elasticsearch-sync#5]
Hi,

see https://github.com/elastic/elasticsearch/issues/13740

I am using the transform function to rename _id to id to avoid the following error. 

> MapperParsingException[Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.]

There was no error from elasticsearch-sync. 

It will be great if elasticsearch-sync can automatically do a rename (default/configurable).

**Comment by toystars** [comment]
Good point you got there. There is an inbuilt transform function that gets called whenever document(s) is about to be indexed in ES. The function is what eventually calls the watcher transform function. It looks like this:

```
/*
 * Function to handle transformation
 * */
ESMongoSync.Util.transform = (watcher, document, callBack) => {
  if (document.index) {
    callBack(document);
  } else {
    if (watcher.transformFunction) {
      watcher.transformFunction(watcher, document, callBack);
    } else {
      document.id = document._id;
      delete document._id;
      callBack(document);
    }
  }
};
```

It handles renaming and removal of the `_id` metafield only if no transform function is provided in the collection watcher. But I guess it should do that irrespective of the presence or absence of the transform function.

I'll look into it and adjust as necessary. Cheers.

**Comment by toystars** [comment]
@siyong PR #6 takes care of this issue.
